config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # devise_scope :user do
  #   get 'login', to: 'devise/sessions#new'
  #   post ''
  # end

  devise_for :users, skip: [:sessions]
  devise_scope :user do
    get 'signin', to: 'devise/sessions#new', as: :new_user_session
    get 'signup', to: 'devise/registrations#new'
    post 'signin', to: 'devise/sessions#create', as: :user_session
    match 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via
  end

  root 'static_pages#home'

  # post '/login', to: 'static_pages#login_form'
  # get '/login', to: 'static_pages#login'

  authenticate :user do
    get 'clubs/district/:district_slug', to: 'clubs#by_district', constrainsts: { district_slug: /[a-z][a-z\-]*[a-z]/ }, as: :district_club

    resources :clubs do
      resources :members do
        post 'affiliate'
      end
    end
    resources :users
    resources :provinces, param: :slug, constraints: { slug: /[a-z][a-z\-]*[a-z]/ }
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/tablists/_clubs.html.erb
<% current_tab = local_assigns.fetch(:current_tab) %>

<nav>
  <ul class="nav nav-tabs nav-tabs-header">

    <li class="<%= current_tab == 'new' ? 'active' : '' %>">
      <%= link_to new_club_path do %>
        <span class="glyphicon glyphicon-plus-sign offset-right" aria-hidden="true"></span>
        <span class="hidden-xs">New Club</span>
      <% end %>
    </li>

  </ul>
</nav>

app/views/partials/tablists/_members.html.erb
<% current_tab = local_assigns.fetch(:current_tab) %>

<nav>
  <ul class="nav nav-tabs nav-tabs-header">

    <li class="<%= current_tab == 'all' ? 'active' : '' %>">
      <%= link_to club_members_path(@club) do %>
        <span class="glyphicon glyphicon-user offset-right" aria-hidden="true"></span>
        <span class="hidden-xs">All Members</span>
      <% end %>
    </li>
    <li class="<%= current_tab == 'new' ? 'active' : '' %>">
      <%= link_to new_club_member_path(@club) do %>
        <span class="glyphicon glyphicon-plus-sign offset-right" aria-hidden="true"></span>
        <span class="hidden-xs">New Member</span>
      <% end %>
    </li>
    <li class="<%= current_tab == 'settings' ? 'active' : '' %>">
      <%= link_to edit_club_path(@club) do %>
        <span class="glyphicon glyphicon-cog offset-right" aria-hidden="true"></span>
        <span class="hidden-xs">Settings</span>
      <% end %>
    </li>

  </ul>
</nav>

app/views/partials/tablists/_users.html.erb
<!-- <% current_tab = local_assigns.fetch(:current_tab) %>

<nav>
  <ul class="nav nav-tabs nav-tabs-header">

    <li class="<%= current_tab == 'all' ? 'active' : '' %>">
      <%= link_to '#' do %>
        <span class="glyphicon glyphicon-user offset-right" aria-hidden="true"></span>
        <span class="hidden-xs">All Members</span>
      <% end %>
    </li>
    <li class="<%= current_tab == 'new' ? 'active' : '' %>">
      <%= link_to '#' do %>
        <span class="glyphicon glyphicon-plus-sign offset-right" aria-hidden="true"></span>
        <span class="hidden-xs">New Member</span>
      <% end %>
    </li>
    <li class="<%= current_tab == 'settings' ? 'active' : '' %>">
      <%= link_to '#' do %>
        <span class="glyphicon glyphicon-cog offset-right" aria-hidden="true"></span>
        <span class="hidden-xs">Settings</span>
      <% end %>
    </li>

  </ul>
</nav> -->