config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # devise_scope :user do
  #   get 'login', to: 'devise/sessions#new'
  #   post ''
  # end

  devise_for :users, skip: [:sessions]
  devise_scope :user do
    get 'signin', to: 'devise/sessions#new', as: :new_user_session
    get 'signup', to: 'devise/registrations#new'
    post 'signin', to: 'devise/sessions#create', as: :user_session
    match 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via
  end

  root 'static_pages#home'

  # post '/login', to: 'static_pages#login_form'
  # get '/login', to: 'static_pages#login'

  authenticate :user do
    get 'clubs/district/:district_slug', to: 'clubs#by_district', constrainsts: { district_slug: /[a-z][a-z\-]*[a-z]/ }, as: :district_club

    resources :clubs do
      resources :members do
        post 'affiliate'
      end
    end
    resources :users
    resources :provinces, param: :slug, constraints: { slug: /[a-z][a-z\-]*[a-z]/ }
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/navbar/_collapsible_menu.html.erb
<!-- Collapsible menu -->
<div class="collapse navbar-collapse" id="mainMenu">

  <ul class="nav navbar-nav" data-nav-name="<%= @nav_category %>">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="Select Province">
        <%= current_province.name %>
        <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span>
      </a>
      <ul class="dropdown-menu">
        <% all_provinces.each do |province| %>
          <li class="dropdown-header <%= (province.id == current_province.id) ? 'active' : '' %>">
            <%= link_to province_url(province) do%>
              <%= province.name %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </li>
    <li class="dropdown <%= @nav_category == 'clubs' ? 'active' : '' %>" >
      <%= link_to '#', class: 'dropdown-toggle', 'data-toggle' => 'dropdown' do %>
        <span class="glyphicon glyphicon-education offset-right" aria-hidden="true"></span>
        <span class="hidden-sm">Clubs</span>
      <% end %>
      <ul class="dropdown-menu">
        <li>
          <%= link_to clubs_path do %>
            All <%= current_province.name %> Clubs
          <% end %>
        </li>
        <li class="divider"></li>
        <% current_province.clubs.sort {|a,b| a.name <=> b.name }.each do |club| %>
          <% if not @club.nil? and @club.id == club.id %>
            <li class="active"><%= link_to club.name, club_path(club) %></li>
          <% else %>
            <li><%= link_to club.name, club_path(club) %></li>
          <% end %>
        <% end %>
        <li class="divider"></li>
        <li>
          <%= link_to new_club_path do %>
            <span class="glyphicon glyphicon-plus-sign offset-right icon-shift-down" aria-hidden="true"></span>
            New Club
          <% end %>
        </li>
      </ul>
    </li>
    <li class="<%= @nav_category == 'competitions' ? 'active' : '' %>">
      <a href="#">
        <span class="glyphicon glyphicon-king offset-right" aria-hidden="true"></span>
        <span class="hidden-sm">Competitions</span>
      </a>
    </li>
  </ul>

  <ul class="nav navbar-nav navbar-right">
    <li class="dropdown <%= @nav_category == 'user_settings' ? 'active' : '' %>">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="My account">
        <span class="glyphicon glyphicon-user offset-right" aria-hidden="true"></span>
        <span class="visible-xs">My account</span>
        <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span>
      </a>
      <ul class="dropdown-menu">
        <li class="dropdown-header">
          <%= link_to edit_user_path(current_user), title: 'Settings' do %>
            <%= current_user.finished_registration? ? current_user.name : 'New User' %>
          <% end %>
        </li>
        <li class="divider"></li>
        <li>
          <%= link_to destroy_user_session_path do %>
            <span class="glyphicon glyphicon-off offset-right icon-shift-down" aria-hidden="true"></span>
            Sign out
          <% end %>
        </li>
      </ul>
    </li><!-- .dropdown -->
  </ul><!-- .nav -->

</div>

app/views/partials/navbar/_top.html.erb
<header role="banner" id="top" class="site-header">

  <!-- Main navigation -->
  <nav class="navbar navbar-fixed-top navbar-primary">
      <div class="container">

          <!-- Brand and menu toggle -->
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mainMenu">
                  <span class="sr-only">Menu</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <%= link_to root_path, class: 'navbar-brand offset-right-large' do %>
                  <span class="visible-xs visible-md visible-lg">Karate Site</span>
                  <span class="visible-sm" aria-hidden="true">KS - SA</span>
              <% end %>

          </div>

          <%= render 'partials/navbar/collapsible_menu' %>

      </div><!-- .container -->
  </nav>

</header>