config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # devise_scope :user do
  #   get 'login', to: 'devise/sessions#new'
  #   post ''
  # end

  devise_for :users, skip: [:sessions]
  devise_scope :user do
    get 'signin', to: 'devise/sessions#new', as: :new_user_session
    get 'signup', to: 'devise/registrations#new'
    post 'signin', to: 'devise/sessions#create', as: :user_session
    match 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via
  end

  root 'static_pages#home'

  # post '/login', to: 'static_pages#login_form'
  # get '/login', to: 'static_pages#login'

  authenticate :user do
    get 'clubs/district/:district_slug', to: 'clubs#by_district', constrainsts: { district_slug: /[a-z][a-z\-]*[a-z]/ }, as: :district_club

    resources :clubs do
      resources :members do
        post 'affiliate'
      end
    end
    resources :users
    resources :provinces, param: :slug, constraints: { slug: /[a-z][a-z\-]*[a-z]/ }
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :club
  attr_accessor :age, :full_name

  mount_uploader :avatar, MemberAvatarUploader

  validates :first_name,
      presence: true,
      length: {
        minimum: 3,
      }
  validates :last_name,
      presence: true,
      length: {
        minimum: 3,
      }
  validates :date_of_birth,
      presence: true
  validates :email,
      format: { with: Devise.email_regexp }

  def age
    now = Time.now.utc.to_date
    now.year - self.date_of_birth.year - ((now.month > self.date_of_birth.month || (now.month == self.date_of_birth.month && now.day >= self.date_of_birth.day)) ? 0 : 1)
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:affiliate, :show, :edit, :update, :destroy]
  before_action :set_members, only: [:index]
  before_action :load_club

  before_action :set_nav_category

  add_breadcrumb 'Club', :club_path
  add_breadcrumb 'Members', :club_members_path

  # POST /members/1/affiliate
  def affiliate
    @member.is_affiliated = !@member.is_affiliated
    if @member.save
      render json: { result: 'success', is_affiliated: @member.is_affiliated }
    else
      render json: { result: 'failure', is_affiliated: @member.is_affiliated }
    end
  end

  # GET /members
  # GET /members.json
  def index
    # @members = @club.members.order(last_name: :asc, first_name: :asc)
    respond_to do |format|
      format.html
      format.xlsx do
        render xlsx: 'index', filename: "DojoForm_#{@club.name}.xlsx"
      end
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "#{@club.name} - #{@member.first_name} #{@member.last_name}",
               show_as_html: Rails.env.development? && params.key?('debug'),
               layout: 'pdf.html'
      end
    end
  end

  # GET /members/new
  def new
    @member = @club.members.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = @club.members.build(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to club_member_path @club, @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to club_member_path @club, @member } #, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url } #, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      load_club
      member_id = (params[:id] || params[:member_id])
      @member ||= @club.members.where(id: member_id).first

      # Ensure that the user asked for is in the list for this dojo.
      if not @member
        redirect_to club_members_path @club
      end
    end

    def set_members
      load_club
      @members ||= @club.members
    end

    def load_club
      club_id = params[:club_id]
      @club ||= Club.find(club_id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:first_name,
        :last_name,
        :date_of_birth,
        :race,
        :residential_address,
        :code,
        :cell_number,
        :email,
        :current_weight,
        :current_height,
        :belt,
        :is_affiliated,
        :avatar,
        :remove_avatar)
    end

    def set_nav_category
      @nav_category = 'clubs'
    end

end

app/helpers/members_helper.rb
module MembersHelper

  def belt_options
    belts = Member.select('DISTINCT belt').collect(&:belt).collect {|b| [b, b]}
  end

end

app/views/members/_form.html.erb
<%= form_with(model: [@club, member], local: true) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset class="offset-bottom">
    <legend>Member Info</legend>
    <div class="row">
      <div class="col-sm-6">

        <div class="form-group">
          <%= form.label :first_name %>
          <%= form.text_field :first_name, id: :member_first_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= form.label :last_name %>
          <%= form.text_field :last_name, id: :member_last_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= form.label :date_of_birth %>
          <%= form.date_select :date_of_birth, id: :member_date_of_birth, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= form.label :avatar %>
          <%= form.file_field :avatar, id: :member_avatar, class: 'form-control' %>
          <% if form.object.avatar? %>
            <%= image_tag form.object.avatar.url %>
            <%= form.label :remove_image %>
            <%= form.check_box :remove_avatar %>
          <% end %>
        </div>
        <div class="form-group">
          <%= form.label :race %>
          <%= form.text_field :race, id: :member_race, class: 'form-control' %>
        </div>

      </div>
      <div class="col-sm-6">

        <div class="form-group">
          <%= form.label :residential_address %>
          <%= form.text_field :residential_address, id: :member_residential_address, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :code %>
          <%= form.text_field :code, id: :member_code, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :cell_number %>
          <%= form.text_field :cell_number, id: :member_cell_number, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :email %>
          <%= form.text_field :email, id: :member_email, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :current_weight %>
          <%= form.number_field :current_weight, id: :member_current_weight, class: 'form-control' %>
        </div>
      </div>
    </div> <!-- .row -->
  </fieldset>
  <fieldset class="offset-bottom">
    <legend>Other stuffs</legend>

    <div class="form-group">
      <%= form.label :current_height %>
      <%= form.number_field :current_height, id: :member_current_height, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :belt %>
      <%= form.select(:belt, belt_options, {}, {id: :member_belt, class: 'form-control'}) %>
    </div>

    <div class="form-group">
      <%= form.label :is_affiliated %>
      <%= form.check_box :is_affiliated, id: :member_is_affiliated, class: 'form-control' %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  </fieldset>
<% end %>

app/views/members/_member.html.erb
<section class="section-content">
  <div class="container">
    <div class="row">
      <div class="col-xs-5">
        <h5><em>First name:</em></h5>
        <p>
          <%= @member.first_name %>
        </p>
      </div>
      <div class="col-xs-7">
        <h5><em>Last name:</em></h5>
        <p>
          <%= @member.last_name %>
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-5">
        <h5><em>Residential Address:</em></h5>
        <p>
          <%= @member.residential_address %>
        </p>
      </div>

      <div class="col-xs-4">
        <h5><em>Code:</em></h5>
        <p>
          <%= @member.code %>
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-5">
        <h5><em>Cell Number:</em></h5>
        <p>
          <%= @member.cell_number %>
        </p>
      </div>
      <div class="col-xs-7">
        <h5><em>Email:</em></h5>
        <p>
          <%= @member.email %>
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-5">
        <h5><em>Current Weight:</em></h5>
        <p>
          <%= @member.current_weight || 'N/A' %>
        </p>
      </div>
      <div class="col-xs-7">
        <h5><em>Current Height:</em></h5>
        <p>
          <%= @member.current_height || 'N/A' %>
        </p>
      </div>
    </div>
    <div class="row divider ">
    </div>
    <div class="row">
      <div class="col-xs-7">
        <h5><em>Club Name:</em></h5>
        <p>
          NAME Of CLUB HERE
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-5">
        <h5><em>Club Cell:</em></h5>
        <p>
          Cell of Club HERE
        </p>
      </div>
      <div class="col-xs-7">
        <h5><em>Email:</em></h5>
        <p>
          Club email here
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-5">
        <h5><em>Sensei Name:</em></h5>
        <p>
          Name of Sensei here
        </p>
      </div>
      <div class = "col-xs-7">
        <h5><em>District:</em></h5>
        <p>
          District goes HERE
        </p>
      </div>
    </div>
  </div>
</section>

app/views/members/edit.html.erb
<%= render 'partials/headline',
    headline: @club.name,
    page_name: 'members',
    current_tab: '' %>

<div class="section-content">
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <%= render 'form', member: @member %>
      </div>
    </div>
  </div>
</div>

app/views/members/index.html.erb
<%= render 'partials/headline',
    headline: @club.name,
    page_name: 'members',
    current_tab: 'all' %>

<div class="section-content">
  <div class="container">
    <div class="row">
      <div class="col-xs-7 offset-bottom">
        <!-- <%= link_to new_club_member_path(@club), class: 'btn btn-warning btn-raised' do %>
          <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
          New Member
        <% end %> -->
        <div class="input-group has-feedback has-feedback-right">
          <div class="input-group-btn">
            <button id="current-search"
                type="button"
                class="btn btn-default dropdown-toggle"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
                data-search-field="name">
              Name
            </button>
            <!-- values are brought in from members.coffee -->
            <ul id="other-fields" class="dropdown-menu">
              <!-- <li><a href="#" data-search-field="belt">Belt</a></li>
              <li><a href="#">Affiliated</a></li> -->
            </ul>
          </div><!-- .btn-group -->
          <input id="search-input" type="text" class="form-control" aria-label="search" />
          <i class="form-control-feedback glyphicon glyphicon-search"></i>

          <!-- <div class="row">
            <div class="col-xs-6">
              <input id="search-input" type="text" class="form-control"  aria-label="search"/>
            </div> -->
            <!-- <div class="col-xs-2"> -->
              <!-- <label class="switch ">
                <input type="checkbox">
                <span class="slider"></span>
              </label> -->
            <!-- </div> -->
          <!-- </div> -->

        </div><!-- .input-group -->

      </div>
      <div class="col-xs-4 offset-bottom pull-right orrset-right">
        <div class="btn-group pull-right">
          <%= link_to club_members_url(@club, format: :xlsx), class: 'btn btn-primary' do %>
            <span class="glyphicon glyphicon-save" aria-hidden="true"></span>
          <% end %>
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="caret"></span>
            <span class="sr-only">Toggle Dropdown</span>
          </button>
          <ul class="dropdown-menu dropdown-menu-right">
            <li><a href="#">Action</a></li>
            <li><a href="#">Other action</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated Link</a></li>
          </ul>
        </div>
      </div>
    </div><!-- .row -->
    <div class="table-responsive table-responsive-dropdowns">
      <table class="table table-hover">
        <thead>
          <tr>
            <!-- <th class="table-cell-id">#</th> -->
            <!-- <th data-toggle="sort" data-sort-onload="asc" class="col-sm-3" tabindex="0">Date</th> -->
            <th class="col-sm-3" tabindex="0">Name</th>
            <th class="col-sm-2" tabindex="0">Belt</th>
            <!-- <th data-toggle="sort" class="col-sm-3 text-right" tabindex="0">Race</th> -->
            <th class="col-sm-2 text-center">Age</th>
            <th class="col-sm-3 text-center" tabindex="0">Affiliation</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @members.each_with_index do |member, index| %>
            <tr class="member_row">
              <!-- <td class="table-cell-id">
                <%= member.id %>
              </td> -->
              <td data-search-field="name">
                <%= link_to club_member_path(@club, member), class: 'text-nowrap' do %>
                  <%= member.first_name %>
                  <%= member.last_name %>
                <% end %>
              </td>
              <td data-search-field="belt">
                <div class="small text-nowrap">
                  <%= member.belt %>
                </div>
              </td>
              <td class="text-center" data-search-field="age">
                <%= member.age %>
              </td>
              <td class="text-center affiliation_badge" data-search-field="affiliated">
                <%= render 'components/affiliation_badge', is_affiliated: member.is_affiliated %>
              </td>
              <td class="table-cell-actions">
                <%= link_to edit_club_member_path(@club, member), class: 'item-action', title: 'Edit' do %>
                  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                <% end %>
                <%= link_to club_member_affiliate_path(@club, member), class: 'item-action mark-aff-link', title: 'Mark as affiliated', remote: true, method: :post do %>
                  <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                <% end %>
                <div class="btn-group">
                  <button class="item-action" type="button" id="itemOptions<%= index %>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="glyphicon glyphicon-option-vertical" aria-hidden="true"></span>
                  </button>
                  <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="itemOptions<%= index %>">
                    <li>
                      <%= link_to club_member_path(@club, member), data: {
                        'toggle' => 'confirm',
                        'confirm-message' => "Do you really want to remove this member?",
                        'confirm-yes' => "Yes",
                        'confirm-no' => "No"
                      }, method: :delete do %>

                        <span class="glyphicon glyphicon-remove-sign offset-right" aria-hidden="true"></span>
                        Remove member
                      <% end %>
                    </li>
                  </ul>
                </div>
              </td>
            </tr>
          <% end %>

        </tbody>
      </table>

      <div class="hidden">
        <div id="affiliated-logo">
          <%= render 'components/affiliation_badge', is_affiliated: true %>
        </div>
        <div id="not-affiliated-logo">
          <%= render 'components/affiliation_badge', is_affiliated: false %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/members/new.html.erb
<%= render 'partials/headline',
    headline: @club.name,
    page_name: 'members',
    current_tab: 'new' %>



<div class="secion-content">
  <div class="container">

    <h1>New Member</h1>

    <%= render 'form', member: @member %>
  </div>
</div>

app/views/members/show.html.erb
<%= render 'partials/headline',
    headline: @club.name,
    page_name: 'members',
    current_tab: '' %>


<div class="section-content">
  <div class="container">



    <p id="notice"><%= notice %></p>
<%= render_breadcrumbs %>
<section class="sectoin-header section-header-condensed">
  <div class="row">
    <div class="container col-xs-12">

    </div>
  </div>
  <div class="row">
    <div class="container col-xs-9">
      <h1 class="section-header-title">Member Profile</h1>
      <!-- <h2 class="secltion-header-subtitle">Club Name</h2> -->
    </div><!-- .container -->
    <div class="container col-xs-2 pull-right">
      <div class="offset-bottom pull-right">
        <div class="btn-group">
          <%= link_to club_member_path(@club, @member, format: :pdf), class: 'btn btn-primary' do %>
            <span class="glyphicon glyphicon-save" aria-hidden="true"></span>
          <% end %>
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="caret"></span>
            <span class="sr-only">Toggle Dropdown</span>
          </button>
          <ul class="dropdown-menu dropdown-menu-right">
            <li><%= link_to 'Edit', edit_club_member_path(@club, @member) %></li>
            <li><a href="#">Action</a></li>
            <li><a href="#">Other action</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated Link</a></li>
          </ul>
        </div>
      </div>
    </div><!-- .container -->
  </div><!-- .row -->
</section>
<section class="section-content">
  <div class="container">
    <div class="row offset-bottom">
      <h4>Member Image:</h4>
      <% if not @member.avatar.url.nil? %>
        <%= image_tag @member.avatar.url, size: 140 %>
      <% end %>
    </div>
    <div class="row">
      <div class="col-sm-5">
        <h4>First name:</h4>
        <p>
          <%= @member.first_name %>
        </p>
      </div>
      <div class="col-sm-7">
        <h4>Last name:</h4>
        <p>
          <%= @member.last_name %>
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <h4>Residential Address:</h4>
        <p>
          <%= @member.residential_address %>
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-4">
        <h4>Code:</h4>
        <p>
          <%= @member.code %>
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-5">
        <h4>Cell Number:</h4>
        <p>
          <%= @member.cell_number %>
        </p>
      </div>
      <div class="col-sm-7">
        <h4>Email:</h4>
        <p>
          <%= @member.email %>
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-5">
        <h4>Current Weight:</h4>
        <p>
          <%= @member.current_weight || 'N/A' %>
        </p>
      </div>
      <div class="col-sm-7">
        <h4>Current Height:</h4>
        <p>
          <%= @member.current_height || 'N/A' %>
        </p>
      </div>
    </div>
    <div class="row divider">
    </div>
    <div class="row">
      <div class="col-sm-7">
        <h4>Club Name:</h4>
        <p>
          <%= @club.name %>
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-5">
        <h4>Club Cell:</h4>
        <p>
          <%= @club.cell %>
        </p>
      </div>
      <div class="col-sm-7">
        <h4>Email:</h4>
        <p>
          <%= @club.email %>
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-7">
        <h4>Sensei Name:</h4>
        <p>
          <%= @club.sensei %>
        </p>
      </div>
    </div>
    <div class="row">
      <div class = "col-sm-7">
        <h4>District</h4>
        <p>
          District goes HERE
        </p>
      </div>
    </div>
  </div>

</div>
</section>
</div>
</div>

app/views/members/show.pdf.erb
<h1>GAUTENG KARATE FEDERATION</h1>
<h3>STUDENT AFFILIATION FORM - <%= Time.now.year %></h3>
<div class="container">
  <div class="row">
    <% if @member.avatar.url.nil? %>
      <%= wicked_pdf_image_tag('default_member.jpg', size: 140) %>
    <% else %>
      <%= wicked_pdf_image_tag(@member.avatar.url, size: 140) %>
    <% end %>
    <div class="pull-right">
      <%= wicked_pdf_image_tag('jkf_logo.png', size: 140) %>
    </div>
  </div>
</div>
<%= render :partial => 'members/member.html', :object => @member %>